version: '3.8'

services:
  db:
    image: postgres:14
    container_name: dataking_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dataking
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: dataking_backend
    ports:
      - "8000:8000"
    environment:
      PGHOST: db
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: dataking
      PGPORT: 5432
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: dataking_frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  pgdata:
